-- Daily Thought: seed catalogue of original, unattributed thoughts.
-- Safe to re-run: existing bodies are skipped.
-- 64 entries, so the 60-day no-repeat window always leaves a fresh choice.

insert into public.thoughts (body) values
  ('Small steps taken daily outrun big plans made occasionally.'),
  ('You do not need to feel ready. You only need to begin.'),
  ('Rest is not a reward for finishing. It is part of the work.'),
  ('Notice one thing today that you usually walk past.'),
  ('A calm answer is often the strongest one in the room.'),
  ('What you practise quietly becomes who you are loudly.'),
  ('Let today be enough, even if it is not everything.'),
  ('Curiosity is a kinder teacher than fear.'),
  ('The kindest thing you can do for your future self is start now.'),
  ('Progress looks messy from the inside. Keep going anyway.'),
  ('You can be a work in progress and still be worth celebrating.'),
  ('Listen long enough and people will tell you what they need.'),
  ('Your attention is a gift. Spend it on what deserves it.'),
  ('Do the next right thing, then the one after that.'),
  ('Clarity often arrives after action, not before it.'),
  ('A single honest sentence can open a door that silence keeps shut.'),
  ('Be patient with slow growth. Roots grow before branches.'),
  ('It is fine to change your mind when you learn something new.'),
  ('Make room for joy in the ordinary parts of the day.'),
  ('Comparison steals the view from your own path.'),
  ('Finish something small today and let it count.'),
  ('A hard day is still a day you showed up for.'),
  ('Ask one more question before you decide.'),
  ('Gratitude turns what you have into enough.'),
  ('The habit you keep on bad days is the one that shapes you.'),
  ('Speak to yourself the way you would speak to a friend.'),
  ('Simple is not the same as easy, but it is usually worth it.'),
  ('Every expert once stood exactly where you stand now.'),
  ('Protect your mornings and your mornings will protect you.'),
  ('Mistakes are receipts for things you tried.'),
  ('When in doubt, slow down and breathe before you choose.'),
  ('You are allowed to outgrow the version of you that others expect.'),
  ('A tidy space leaves more room for a clear mind.'),
  ('Generosity costs little and returns more than it spends.'),
  ('The present moment is the only place where change can happen.'),
  ('Courage is often just a quiet decision to try again tomorrow.'),
  ('Put down one worry today. You can pick it up later if you must.'),
  ('Learning is the one investment that never loses its value.'),
  ('Say no to something small so you can say yes to something that matters.'),
  ('A walk outside can solve problems a screen cannot.'),
  ('Your pace is valid, even when it is slower than someone else''s.'),
  ('Kind words are remembered long after clever ones are forgotten.'),
  ('Turn one "I should" into "I will" today.'),
  ('Discipline is choosing what you want most over what you want now.'),
  ('There is strength in asking for help.'),
  ('Look for the lesson, not the blame.'),
  ('Your future is built in ordinary Tuesdays.'),
  ('Leave a place a little better than you found it.'),
  ('Doubt is a visitor. It does not have to move in.'),
  ('Water what you want to grow, including your own ideas.'),
  ('Silence can be a good answer while you find a better one.'),
  ('Focus on what you can control and loosen your grip on the rest.'),
  ('Wonder is always available if you remember to look up.'),
  ('A promise kept to yourself builds trust from the inside out.'),
  ('Celebrate the effort, not only the outcome.'),
  ('Some days the win is simply being gentle with yourself.'),
  ('Write it down. A clear page makes a clear head.'),
  ('You can start the day over at any hour you choose.'),
  ('Keep a little room in your plans for surprise.'),
  ('Patience is not waiting. It is how you behave while you wait.'),
  ('The best time to repair a friendship is before it breaks.'),
  ('Choose progress over perfection, and repeat.'),
  ('Your energy is information. Notice what gives and what takes it.'),
  ('End the day by naming one thing that went right.')
on conflict (body) do nothing;
